name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - 1.0.x
    tags-ignore:
      - v*

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  connectors:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - { connector: mqtt-streaming,               pre_cmd: 'docker-compose up -d mqtt' }

    env:
      JAVA_OPTS: -Xms2G -Xmx3G -Xss2M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6

      - name: ${{ matrix.connector }}
        env:
          CONNECTOR: ${{ matrix.connector }}
          PRE_CMD: ${{ matrix.pre_cmd }}
        run: |-
          $PRE_CMD
          sbt "+${CONNECTOR}/test"

      - name: Print logs on failure
        if: failure()
        run: find . -name "*.log" -exec ./scripts/cat-log.sh {} \;
