name: Link Validator

on:
  schedule:
    - cron:  '0 6 * * 1'

jobs:
  validate-links:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: # https://github.com/olafurpg/setup-scala#faster-checkout-of-big-repos
          fetch-depth: 100

      - name: Fetch tags
        run: git fetch --depth=100 origin +refs/tags/*:refs/tags/*

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: sbt site
        run: sbt docs/makeSite

# TODO: Fix after documentation updates
#      - name: Run Link Validator
#        run: cs launch net.runne::site-link-validator:0.2.2 -- scripts/link-validator.conf
